### ISSUE TITLE
Add Mode and Config to begin()

### ISSUE THREAD

**Issue by XavierBril** [asukiaaa/SomeSerial#2]
Would it be possible to add the mode and config parameter to the begin() function?

Thanks
XB

**Comment by asukiaaa** [comment]
How?
By the way, variables for begin are different between [hardware serial](https://www.arduino.cc/reference/en/language/functions/communication/serial/begin/) and [software serial](https://www.arduino.cc/en/Reference/SoftwareSerialBegin).
So if you want to initialize with specifying value except for baudrate, you should put serial to someserial after begining like this.

```cpp
SomeSerial *mySerial;

void setup() {
  Serial1.begin(115200, SERIAL_7E2);
  mySerial = new SomeSerial(&Serial1);
}
```

**Comment by XavierBril** [comment]
thanks for your kind reply,

You're right, there is a limitation due to softserial library not implementing the parity. I wanted to try to use modbus over softserial (using the arduino as master) and the standard would require to support even parity at least, I'll try to make do with hardserial only
